"""LLM Provider abstraction and request/response models.

Isolates InvestIQ from specific vendor SDKs (e.g. Gemini, OpenAI) and guarantees
structured output generation, cost metadata tracking, and cost safety controls.
"""

from abc import ABC, abstractmethod
from typing import Any, Generic, TypeVar

from pydantic import BaseModel, Field


T = TypeVar("T", bound=BaseModel)


class CostGuardError(RuntimeError):
    """Raised when a real external LLM API is requested without explicit production authorization."""

    pass


class LLMRequest(BaseModel):
    """Encapsulates all parameters for an LLM generation call.

    Attributes:
        prompt: User/system prompt string.
        model: Target model identifier (e.g., "gemini-1.5-pro", "mock-analyst-v1").
        temperature: Sampling temperature.
        max_tokens: Generation limit.
        system_instruction: System prompt framing context.
        valid_evidence_ids: Evidence IDs valid for the current request context.
                           Used by mock provider to generate valid evidence references.
    """

    prompt: str
    model: str = "mock-financial-analyst-v1"
    temperature: float = 0.2
    max_tokens: int = 2048
    system_instruction: str | None = None
    valid_evidence_ids: list[str] | None = None


class LLMResponse(BaseModel, Generic[T]):
    """Standardized response from an LLM call carrying cost and performance metadata.

    Attributes:
        output: Parsed structured output matching requested response schema.
        raw_text: Raw string generated by the model.
        model: Model identifier that performed the generation.
        input_tokens: Count of prompt tokens.
        output_tokens: Count of generated completion tokens.
        latency_ms: Execution duration in milliseconds.
        cache_hit: True if response was served from LLM cache.
        estimated_cost: Calculated cost in USD based on model pricing.
    """

    output: Any  # Type T instance
    raw_text: str | None = None
    model: str
    input_tokens: int = 0
    output_tokens: int = 0
    latency_ms: float = 0.0
    cache_hit: bool = False
    estimated_cost: float = 0.0


class LLMProvider(ABC):
    """Abstract base class for LLM providers."""

    @abstractmethod
    def generate_structured(
        self,
        request: LLMRequest,
        response_schema: type[T],
    ) -> LLMResponse[T]:
        """Generate structured output validated against a Pydantic schema."""
        pass
